#remote_theme: tschneidereit/type-theme
plugins:
  - jekyll-include-cache
  - jekyll-wit

theme_settings:
  github: bytecodealliance/wasi.dev
  avatar: polyfill/WASI-small.png

exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-wit